@baseUrl = http://localhost:5129

@accessToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjFmM2ZkNDBhLTk4MWQtNDI2My04Yzk3LWJkZWUwOTczNjNmNyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJUZXN0IFVzZXIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBRE1JTiIsImRlcGFydG1lbnRfaWQiOiIwMTlkY2Y2ZS1iMDJlLTc5YjYtYjRjNS1jZGZlN2FkYjY3NjEiLCJleHAiOjE3Nzc3NDAzMjQsImlzcyI6ImxlYXZlLW1hbmFnZW1lbnQtYXBpIiwiYXVkIjoibGVhdmUtbWFuYWdlbWVudC1hcGktY2xpZW50In0.YYDNbjsCo165YIwupu9AdX4ZmEnrkGPts52wsvMI-Xk
### Login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "Email": "admin@gmail.com",
    "Password": "password"
}

### Create a new user
POST {{baseUrl}}/api/users
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "Email": "admin@gmail.com",
    "PasswordHash": "password",
    "FullName": "Test User",
    "Role": "ADMIN",
    "DepartmentId": "019dcf6e-b02e-79b6-b4c5-cdfe7adb6761",
    "IsActive": true
}

### Get all users (requires Bearer token)
GET {{baseUrl}}/api/users
Authorization: Bearer {{accessToken}}

### Get a specific user by ID
GET {{baseUrl}}/api/users/{79917f5d-1c22-4528-a516-3805c871689b}
Authorization: Bearer {{accessToken}}

### Update a user
PUT {{baseUrl}}/api/users/{79917f5d-1c22-4528-a516-3805c871689b}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "Email": "tes@example.com",
    "PasswordHash": "hashedpassword1",
    "FullName": "Test User 1",
    "Role": "EMPLOYEE",
    "DepartmentId": "019dcf6e-b02e-79b6-b4c5-cdfe7adb6761"
}

### Delete a user
DELETE {{baseUrl}}/api/users/{79917f5d-1c22-4528-a516-3805c871689b}
Authorization: Bearer {{accessToken}}

### Create a new department
POST {{baseUrl}}/api/departments
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "Name": "Mg",
    "Description": "Management Department"
}

### Get all departments
GET {{baseUrl}}/api/departments
Authorization: Bearer {{accessToken}}

### Get a specific department by ID
GET {{baseUrl}}/api/departments/{019dcf6e-b02e-79b6-b4c5-cdfe7adb6761}
Authorization: Bearer {{accessToken}}

### Update a department
PUT {{baseUrl}}/api/departments/{019dcf6e-b02e-79b6-b4c5-cdfe7adb6761}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "Name": "Test1",
    "Description": "Test Department"
}

### Delete a department
DELETE {{baseUrl}}/api/departments/{019dd2d6-cfd6-78f4-bd7d-2178fe6a2e8b}
Authorization: Bearer {{accessToken}}

